part of 'productss_cubit.dart';

@immutable
abstract class ProductssState {}

final class ProductssInitial extends ProductssState {}

final class ProductssLoading extends ProductssState {
  List<ProductModel> products = [
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
    ProductModel(
      id: 1,
      title: 'Product 1',
      description: 'Description 1',
      category: 'Category 1',
      price: 20,
      discountPercentage: 10,
      rating: 30,
      stock: 50,
      brand: 'Brand 1',
      thumbnail: null,
      reviews: [],
    ),
  ];
}

final class ProductssSuccess extends ProductssState {
  final List<ProductModel> products;

  ProductssSuccess({required this.products});
}

final class ProductssFailure extends ProductssState {
  final String errorMessage;

  ProductssFailure({required this.errorMessage});
}
